# Build using Alire. 
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, ubuntu-18.04]

    steps:    
       - name: Checkout
         uses: actions/checkout@v2
       - name: ada-actions/toolchain
         uses: ada-actions/toolchain@ce2021
         with:
           distrib: community
           target: native
       - name: alire-project/setup-alire
         uses: alire-project/setup-alire@latest-stable
       - name: Build
         run: alr build
         
  release:
    name: Continuous AppImage
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:    
       - name: Build AppImage
         run: VERSION=continuous make AppImage
       - name: Create Release
         uses: ncipollo/release-action@v1
         with:
           allowUpdates: True
           tag: continuous
           name: Continuous build
           prerelease: True
           artifacts: "Play_2048*.AppImage"
           token: ${{ secrets.GITHUB_TOKEN }}
