# Build using Alire and deliver a Windows Exe and a Linux AppImage. 
name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:    
       - name: Checkout
         uses: actions/checkout@v2
       - name: ada-actions/toolchain
         uses: ada-actions/toolchain@ce2021
         with:
           distrib: community
           target: native
       - name: alire-project/setup-alire
         uses: alire-project/setup-alire@v5
       - name: Update apt
         if: runner.os == 'Linux'
         run: sudo apt-get update
       - name: Update
         run: alr index --update-all
       - name: Build
         run: alr --non-interactive build
       - name: Install
         run: alr --non-interactive install --prefix=play_2048_folder

       # On Windows, install zip as it is not available by default
       - name: Install zip (Windows)
         if: runner.os == 'Windows'
         run: choco install zip

       - name: Package binaries
         shell: bash
         run: |
           zip -r play_2048-${{ runner.os }}.zip play_2048_folder/

       - name: Create Release
         uses: ncipollo/release-action@v1
         with:
           allowUpdates: True
           tag: continuous
           name: Continuous build
           prerelease: True
           artifacts: "play_2048-${{ runner.os }}.zip"
           token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Continuous AppImage
    runs-on: ubuntu-22.04
    steps:    
       - name: Checkout
         uses: actions/checkout@v2
       - name: ada-actions/toolchain
         uses: ada-actions/toolchain@ce2021
         with:
           distrib: community
           target: native
       - name: alire-project/setup-alire
         uses: alire-project/setup-alire@v1
         with:
           version: 1.2.1                
       - name: Update apt
         run: sudo apt-get update
       - name: Update
         run: alr index --update-all
       - name: Build
         run: alr --non-interactive build
       - name: Build AppImage
         run: VERSION=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}} make AppImage
       - name: Create Release
         uses: ncipollo/release-action@v1
         with:
           allowUpdates: True
           tag: continuous
           name: Continuous build
           prerelease: True
           artifacts: "Play_2048*.AppImage"
           token: ${{ secrets.GITHUB_TOKEN }}
